apiVersion: v1
kind: Service
metadata:
  name: edge-service
spec:
  selector:
    app.kubernetes.io/name: edge
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9999
  allocateLoadBalancerNodePorts: true